export const Message = {
  SUCCESS: "success",
  USER_ALREADY_EXIST_MSG: "User already exist",
  CATEGORY_EXIT_MESSAGE: "Category already exist",
  NO_RECORD_FOUND: "No record found",
  TOKEN_REQUIRED: "Token is required",
  TOKEN_INVALID: "Invalid token",
  INVALID_OTP: "Invalid OTP",
  SOMETHING_WENT_WRONG:"Something went wrong",
  INTERVAL_SERVER_ERROR:"Internal server error",
  EMAIL_ALREADY_EXIST:"Email already exist",
  EMAIL_NOT_FOUND:"Email not found",
  INVALID_CREDENTIAL:"Invalid credential",
  TITLE_ALREADY_EXIST:"Title already exist",
  CATEGORY_NOT_FOUND:"Category not found",
  SINGER_EXIT_MESSAGE: "Singer already exist",
  ALBUM_EXIT_MESSAGE: "Album already exist",
  SONG_NOT_EXIST:"Song not exist",
  SONG_SINGER_ALREADY_EXIST:"Song singer already exist",
  SONG_SINGER_NOT_FOUND:"Song singer not found",
  CATEGORY_NAME_ALREADY_EXIST:"Category name alreday exist"
};
